name: supply_chain

profile: supply_chain

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  supply_chain:
    +schema: raw

models:
  supply_chain:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table

dbt-cloud:
    project-id: 70471823519206